# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.5.2
  hooks:
    - id: isort
- repo: https://github.com/hadialqattan/pycln
  rev: v1.3.2 # Possible releases: https://github.com/hadialqattan/pycln/releases
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=pylintrc", # Link to your config file
        ]
